version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.nodejs
    ports:
      - '8071:8071' # 将前端应用的 3000 端口映射到宿主机的 3000 端口

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - '8073:8073' # 将 Nginx 服务器的 80 端口映射到宿主机的 80 端口
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 映射 Nginx 配置文件到容器内部

networks:
  default:
    driver: bridge
