export interface Repo {
  message: string;
  name: string;
  followers: number;
  location: string;
  company: string;
  avatar_url: string;
  login: string;
  html_url: string;
  following: number;
  id: number;
  node_id: string;
  gravatar_id: string;
  url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  blog: string;
  bio: string;
  public_repos: number;
  public_gists: number;
  created_at: string;
  updated_at: string;
  owner: {
    login: string;
    avatar_url: string;
  };
  stargazers_count: number;
  forks: number;
  open_issues: number;
}
